version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db-security-issues-backend
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: security-issues
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d security-issues"]
      interval: 10s
      timeout: 5s
      retries: 5
  webapp:
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    container_name: dotnet-security-issues-backend
    environment:
       ASPNETCORE_ENVIRONMENT: "Development"
       POSTGRES__HOSTNAME: "postgres-db-security-issues-backend"
       POSTGRES__PORT: "5432"
       POSTGRES__DATABASE: "security-issues"
       POSTGRES__USERNAME: "admin"
       POSTGRES__PASSWORD: "admin"

    build:
      context: .
      dockerfile: Dockerfile    
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata: